"use client"
import "./globals.css";
import {
    QueryClient,
    QueryClientProvider,
} from '@tanstack/react-query'
import { Inter } from "next/font/google";
import LeftSidebar from "@/lib/components/LeftSidebar/LeftSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const queryClient = new QueryClient()

export default function RootLayout({ children }) {
    return (
        <QueryClientProvider client={queryClient}>
            <html lang="en">
                <body className={inter.className + " md:flex"}>
                    <LeftSidebar />
                    <main className="w-full p-3 lg:p-10">
                        {children}
                    </main>
                </body>
            </html>
        </QueryClientProvider>
    );
}
